### PR TITLE
remove 'root' Module.php as already in src/SamUser ( psr-2)

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by manuakasam** [comment]
Does ZF2 by now go deeper into the srcs directory?
This doesn't fail when removed? really don't know :D

**Comment by samsonasik** [comment]
No, it is just a way to make we rely only to composer, and the autoloader already covered. installing other modules/dependencies one by one is a pain

**Comment by samsonasik** [comment]
I removed in DoctrineORMModule too and it works https://github.com/doctrine/DoctrineORMModule/pull/389

**Comment by manuakasam** [comment]
That's interesting. So it just accessing the class after all and doesn't go by filename. Really interesting, didn't know that yet :) Makes stuff more easy.

**Comment by samsonasik** [comment]
thanks, created new PR for removing <code>Module::getAutoladerConfig()</code> at #8

**Pull request merged**
